### ISSUE TITLE
Unhandled exception while trying to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by probonopd** [libscie/hyperdaemon#42]
Unhandled exception while trying to run on Ubuntu 16.04:

```
/tmp/.mount_BeingTWjwYHi/AppRun: Bourne-Again shell script, ASCII text executable

-rwxr-xr-x 1 root root 2.4K Apr 20 13:55 /tmp/.mount_BeingTWjwYHi/AppRun

kernel.unprivileged_userns_clone = 1

A JavaScript error occurred in the main process

Uncaught Exception:

TypeError: Cannot read property 'hide' of undefined

    at Object.<anonymous> (/run/firejail/appimage/.appimage-9318/resources/app.asar/index.js:130:10)

    at Module._compile (internal/modules/cjs/loader.js:880:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)

    at Module.load (internal/modules/cjs/loader.js:735:32)

    at Module._load (internal/modules/cjs/loader.js:648:12)

    at Module._load (electron/js2c/asar.js:717:26)

    at Function.Module._load (electron/js2c/asar.js:717:26)

    at Object.<anonymous> (electron/js2c/browser_init.js:5634:12)

    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:5641:30)

    at __webpack_require__ (electron/js2c/browser_init.js:20:30)

(node:5) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hide' of undefined

    at App.<anonymous> (/run/firejail/appimage/.appimage-9318/resources/app.asar/index.js:120:12)

    at App.emit (events.js:208:15)

(node:5) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hide' of undefined

    at App.<anonymous> (/run/firejail/appimage/.appimage-9318/resources/app.asar/index.js:120:12)

    at App.emit (events.js:208:15)

(node:5) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:5) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:5) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:5) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

0x200003 "hyperdrive-daemon-app": ("hyperdrive-daemon-app" "Hyperdrive-daemon-app")  200x200+0+0  +0+0

0x200001 "hyperdrive-daemon-app": ("hyperdrive-daemon-app" "Hyperdrive-daemon-app")  10x10+10+10  +10+10
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2004

**Comment by juliangruber** [comment]
Thank you for reporting this! We haven’t tested this on Linux yet, thank you for being an early tester 🏎️

**Comment by juliangruber** [comment]
This has been fixed :) Thanks for reporting!
